import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Admin.module.css';

import { useUser, withPageAuthRequired } from '@auth0/nextjs-auth0';
import AdminNavBar from '../../components/Common/AdminNavBar';
import adminImage from "../../public/Assets/Images/admin.jpg";

export default function Admin() {
    return (
        <div>
            <Head>
                <title>Giftroom - Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>

                <AdminNavBar />
                <h2 className='text-3xl text-center mt-2' >Welcome Admin</h2>
                <div className='flex justify-center'>
                    <img className='w-5/12' src={adminImage.src} />
                </div>
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}
