const homePageText = {
    homePageText1: "A Social Platform to Send br and  Collect Digital Assets",
    homePageText2: "Join the waitlist",
    homePageText3: "Subscribe and be notified of upcoming collections",
    homePageText4: "Connect",
    homePageText5: "Designed for everyone",
    homePageText6: "We aim to innovate the world of digital assets. We make blockchain technology easy to use allowing users to send and collect with convenience.",
    homePageText7: "Send and recieve NFTs with or without a digital wallet",
    homePageText8: "Collabrations",
    homePageText9: "We Collaborate with artists, celebrities and charities.",
    homePageText10: "We offer the perfect ability to engage and get acknowledgment from their audience. You can now effortlessly share your appreciation for your favourite content creators, artists and causes.",
    homePageText11: "Get verified and connect with your fan base in a new way",
    homePageText12: "Next-Gen Gifting and Collecting",
    homePageText13: "Socially Interact and Exchange",
    homePageText14: "We offer the perfect ability to engage and get acknowledgment from their audience. You can now",
    homePageText15: "Digital Assets",
    homePageText16: "Send, Recieve or Collect",
    homePageText17: "Send and recieve digital assets with or without a digital wallet",
    homePageText18: "Get in early with the pre-sale our tokens",
    homePageText19: "Send and recieve digital assets with or without a digital wallet",
    homePageText20: "How it Works",
    homePageText21: "Join the waitlist",
    homePageText22: "Subscribe and be notified of upcoming collections",

}

export default homePageText;

    // homePageText23:"Connect",
    // homePageText24:"Connect",
    // homePageText25:"Connect",
    // homePageText26:"Connect",
    // homePageText27:"Connect",
    // homePageText28:"Connect",
    // homePageText29:"Connect",
    // homePageText30:"Connect",