const icoPageText = {
    icoPageText1: "INITIAL COIN OFFERING",
    icoPageText2: "Earlybirds, The br $gifttoken Pre-Sale",
    icoPageText3: "Mission",
    icoPageText4: "Receive free $gift for sending gifts or donations",
    icoPageText5: "We aims to innovate the world of digital assets. We make blockchain technology easy to use with our user-friendly interface allowing users to send and collect with convenience.",
    icoPageText6: "$giftroom",
    icoPageText7: "The giving token that rewards",
    icoPageText8: "We aims to innovate the world of digital assets. We make blockchain technology easy to use with our user-friendly interface allowing users to send and collect with convenience.",
    icoPageText9: "Rewards",
    icoPageText10: "The token that rewards for giving",
    icoPageText11: "We aims to innovate the world of digital assets. We make blockchain technology easy to use with our user-friendly interface allowing users to send and collect with convenience.",
    icoPageText12: "It pays to $gift",
    icoPageText13: "We aims to innovate the world of digital assets.We make blockchain technology easy to use with our user-friendly interface allowing users to send and collect with convenience.",
    icoPageText14: "Tokenomics",
    icoPageText15: "We aims to innovate the world of digital assets.ing users to send and br collect with convenience.",
    icoPageText16: "$giftoken",
    icoPageText17: "Roadmap",
    icoPageText18: "We aims to innovate the world of digital assets.ing users to send and collect with convenience.",
    icoPageText19: "How to buy $giftcoin",
    icoPageText20: "Earlybirds, this is your chance.",
    icoPageText21: "Documents",
    icoPageText22: "Download the whitepaper and learn about ICO Token, the unique ICO Crypto approach and the team/advisors.",

}

export default icoPageText;

    // icoPageText23:"Connect",
    // icoPageText24:"Connect",
    // icoPageText25:"Connect",
    // icoPageText26:"Connect",
    // icoPageText27:"Connect",
    // icoPageText28:"Connect",
    // icoPageText29:"Connect",
    // icoPageText30:"Connect",